"use client";
import { AuthProvider } from "./Providers";
import "./globals.css";
import "@/app/index.css";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import { useEffect } from "react";
import Bootstrap from "@/components/Bootstrap";
import { NextUIProvider } from "@nextui-org/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NextUIProvider>
        <body className={inter.className}>
          <AuthProvider>{children}</AuthProvider>
        </body>
      </NextUIProvider>
    </html>
  );
}
